key = {
    'Cmaj': ['E', 'C', 'G', 'E', 'C', None],
    'Cmin': ['G', 'D#', 'C', 'G', 'C', None], # Cmin ['G', 'Eb', 'C', 'G', 'C', None]
    'Caug' : [None, 'E','C','G#','C',None],
    'Cdim' : ['A','D#', 'C','F#', None, None], # Cdim ['Bbb', 'Eb', 'C', 'Gb', None, None]
    'Cmaj7' : ['E', 'B', 'G', 'E', 'C', None],
    'Cmin7' : ['G', 'D#', 'C', 'G', 'C', None], # Cmin7 ['Bb', 'Eb', 'G', 'G', 'C', None]
    'Cdom7' : ['E', 'C', 'G', 'E', 'C', None], # Cdom7 ['E', 'C', 'Bb', 'E', 'C', None]
    'Cmaj9' : [None, 'D', 'B','E','C', None],
    'Cpmaj' : ['F', 'C#', 'G#', 'F', 'C#', None],
    'Cpmin' : ['G#', 'E', 'C#', 'G#', 'C#', None],
    'Cpaug' : [None, 'F', 'C#', 'A', 'C#', None], # C#aug [None, 'E#', 'C#', 'G##', 'C#', None]
    'Cpdim' : [None, 'E', 'A#', 'G', 'C#', None], # C#dim [None, 'E', 'Bb', 'G', 'C#', None]
    'Cpmaj7' : ['F', 'C', 'G#', 'F', 'C#', None], 
    'Cpmin7' : ['G#', 'E', 'B', 'G#', 'C#', None],
    'Cpdom7' : [None, 'C#', 'B', 'F', 'C#', None],
    'Cpmaj9' : [None, 'D#', 'C', 'F', 'C#', None],
    'Dbmaj' : ['F', 'C#', 'G#', 'F', 'C#', None], # Dbmaj ['F', 'Db', 'Ab', 'F', 'Db', None]
    'Dbmin' : ['G#', 'E', 'C#', 'G#', 'C#', None], # Dbmin ['Ab', 'Fb', 'Db', 'Ab', 'Db', None]
    'Dbaug' : [None, 'F', 'C#', 'A', 'C#', None], # Dbaug [None, 'F', 'Db', 'B', 'Db', None]
    'Dbdim' : [None, 'E', 'A#', 'G', 'C#', None], # Dbdim [None, 'E', 'Bb', 'G', 'Db', None]
    'Dbmaj7' : ['F', 'C', 'G#', 'F', 'C#', None], #['F', 'C', 'Ab', 'F', 'Db', None], 
    'Dbmin7' : ['G#', 'E', 'B', 'G#', 'C#', None], # Dbmin7 ['Ab', 'E', 'B', 'Ab', 'Db', None]
    'Dbdom7' : [None, 'C#', 'B', 'F', 'C#', None], #[None, 'Db', 'B', 'F', 'Db', None]
    'Dbmaj9' : [None, 'D#', 'C', 'F', 'C#', None], #[None, 'Eb', 'C', 'F', 'Db', None],
    'Dmaj' : ['F#', 'D', 'A', 'F#', 'D', None],
    'Dmin' : ['F', 'D', 'A', 'D', None , None],
    'Daug' : [None, 'F#', 'D', 'A#', 'D', None],
    'Ddim' : ['F', 'B', 'G#', 'D', None, None], # ['F', 'B', 'Ab', 'D', None, None],
    'Dmaj7' : ['F#', 'C#', 'A', 'D', None, None],
    'Dmin7' : ['F', 'C', 'A', 'D', None, None],
    'Ddom7' : ['F#', 'C', 'A', 'D', None, None],
    'Dmaj9' : [None, 'E', 'C#', 'F#', 'D', None],
    'Dpmaj' : ['G', 'D#', 'A#', 'G', 'D#', None], 
    'Dpmin' : ['A#', 'F#', 'D#', 'A#', 'D#', None], 
    'Dpaug' : [None, 'G', 'D#', 'B', 'D#', None], 
    'Dpdim' : ['F#', 'C', 'A', 'D#', None, None], 
    'Dpmaj7' : ['G', 'D', 'A#', 'D#', None, None], 
    'Dpmin7' : ['A#', 'F#', 'C#', 'A#', 'S#', None], 
    'Dpdom7' : ['G', 'C#', 'A#', 'D#', None, None], 
    'Dpmaj9' : [None, 'F', 'D', 'G', 'D#', None],
    'Ebmaj' : ['G', 'D#', 'A#', 'G', 'D#', None],  #['G', 'Eb', 'Bb', 'G', 'Eb', None],
    'Ebmin' : ['A#', 'F#', 'D#', 'A#', 'D#', None], #['Bb', 'Gb', 'Eb', 'Bb', 'Eb', None],
    'Ebaug' : [None, 'G', 'D#', 'B', 'D#', None], # [None, 'G', 'Eb', 'B', 'Eb', None],
    'Ebdim' : ['F#', 'C', 'A', 'D#', None, None],  #['Gb', 'C', 'A', 'Eb', None, None],
    'Ebmaj7' : ['G', 'D', 'A#', 'D#', None, None], # ['G', 'D', 'Bb', 'Eb', None, None],
    'Ebmin7' : ['A#', 'F#', 'C#', 'A#', 'D#', None], # ['Bb', 'Gb', 'Db', 'Bb', 'Eb', None]
    'Ebdom7' : ['G', 'C#', 'A#', 'D#', None, None], # ['G', 'Db', 'Bb', 'Eb', None, None],
    'Ebmaj9' : [None, 'F', 'D', 'G', 'D#', None], # [None, 'F', 'D', 'G', 'Eb', None],
    'Emaj' : ['E', 'B', 'G#', 'E', 'B', 'E'],
    'Emin' : ['E', 'B', 'G', 'E', 'B', 'E'],
    'Eaug' : [None, 'C', 'G#', 'E', None, 'E'],
    'Edim' : ['G', 'C#', 'A#', 'E', None, None], # ['G', 'Db', 'Bb', 'E', None, None],
    'Emaj7' : ['G#', 'D#', 'B', 'E', None, None],
    'Emin7' : ['E', 'D', 'G', None, 'B', 'E'],
    'Edom7' : ['E', 'B', 'G#', 'D', 'B', 'E'],
    'Emaj9' : [None, 'F#', 'D#', 'G#', 'E', None],
    'Fmaj' : ['F', 'C', 'A', 'F', 'C', 'F'],
    'Fmin' : ['F', 'C', 'G#', 'F', 'C', 'F'], # ['F', 'C', 'Ab', 'F', 'C', 'F'],
    'Faug' : [None, 'C#', 'A', 'F', None, 'F'],
    'Fdim' : [None, 'B', 'Ab', 'D', None, 'F'], # [None, 'B', 'Ab', 'D', None, 'F'], 
    'Fmaj7' : [None, 'C', 'A', 'E', None, 'F'],
    'Fmin7' : [None, 'C', 'G#', 'D#', None, 'F'], # [None, 'C', 'Ab', 'Eb', None, 'F'],
    'Fdom7' : ['F', 'C', 'A', 'D#', 'C', 'F'], # ['F', 'C', 'A', 'Eb', 'C', 'F'],
    'Fmaj9' : ['G', 'C', 'A', 'E', None, 'F'],
    'Fpmaj' : ['F#', 'C#', 'A#', 'F#', 'C#', 'F#'],
    'Fpmin' : ['F#', 'C#', 'A', 'F#', 'C#', 'F#'],
    'Fpaug' : [None, 'D', 'A#', 'F#', None, 'F#'],
    'Fpdim' : [None, 'C', 'A', 'D#', None, 'F#'], # [None, 'C', 'A', 'Eb', None, 'F#'],
    'Fpmaj7' : [None, 'C#', 'A#', 'F', None, 'F#'],
    'Fpmin7' : [None, 'C#', 'A', 'E', None, 'F#'],
    'Fpdom7' : ['F#', 'C#', 'A#', 'E', 'C#', 'F#'],
    'Fpmaj9' : ['G#', 'C#', 'A#', 'F', None, 'F#'],
    'Gbmaj' : ['F#', 'C#', 'A#', 'F#', 'C#', 'F#'], # ['Gb', 'Db', 'Bb', 'Gb', 'Db', 'Gb'],
    'Gbmin' : ['F#', 'C#', 'A', 'F#', 'C#', 'F#'], # ['Gb', 'Db', 'A', 'Gb', 'Db', 'Gb'], 
    'Gbaug' : [None, 'D', 'A#', 'F#', None, 'F#'], #[None, 'D', 'Bb', 'Gb', None, 'Gb'],
    'Gbdim' : [None, 'C', 'A', 'D#', None, 'F#'], # [None, 'C', 'A', 'Eb', None, 'Gb'],
    'Gbmaj7' : [None, 'C#', 'A#', 'F', None, 'F#'], # [None, 'Db', 'Bb', 'F', None, 'Gb'],
    'Gbmin7' : [None, 'C#', 'A', 'E', None, 'F#'], #[None, 'Db', 'A', 'E', None, 'Gb'],
    'Gbdom7' : ['F#', 'C#', 'A#', 'E', 'C#', 'F#'], # ['Gb', 'Db', 'Bb', 'E', 'Db', 'Gb'],
    'Gbmaj9' : ['A', 'D', 'B', 'F#', None, 'G'], #['A', 'D', 'B', 'F#', None, 'G'],
    'Gmaj' : ['G', 'B', 'G', 'D', 'B', 'G'],
    'Gmin' : ['G', 'D', 'A#', 'G', 'D', 'G'], # ['G', 'D', 'Bb', 'G', 'D', 'G'],
    'Gaug' : [None, 'D#', 'B', 'G', None, 'G'],
    'Gdim' : [None, 'C#', 'A#', 'E', None, 'G'], # [None, 'Db', 'Bb', 'E', None, 'G'],
    'Gmaj7' : [None, 'D', 'B', 'F#', None, 'G'],
    'Gmin7' : [None, 'D', 'A#', 'F', None, 'G'], #[None, 'D', 'Bb', 'F', None, 'G'],
    'Gdom7' : ['F', 'B', 'G', 'D', None, 'G'],
    'Gmaj9' : ['A', 'D', 'B', 'F#', None, 'G'],
    'Gpmaj' : [None, 'C', 'G#', 'D#', None, 'G#'],
    'Gpmin' : ['G#', 'D#', 'B', 'G#', 'D#', 'G#'],
    'Gpaug' : [None, 'E', 'C', 'G#', None, 'G#'],
    'Gpdim' : [None, 'D', 'B', 'F', None, 'G#'],
    'Gpmaj7' : [None, 'D#', 'C', 'G', None, 'G#'],
    'Gpmin7' : [None, 'D', 'C#', 'F', None, 'G'], #[None, 'D', 'Bb', 'F', None, 'G'],
    'Gpdom7' : ['F', 'B', 'G', 'D', None, 'G'], 
    'Gpmaj9' : ['A#', 'D#', 'C', 'G', None, 'G#'],
    'Abmaj' : [None, 'C', 'G#', 'D#', None, 'G#'], # [None, 'C', 'Ab', 'Eb', None, 'Ab'
    'Abmin' : ['G#', 'D#', 'A#', 'G#', 'D#', 'G#'], # ['Ab', 'Eb', 'Bb', 'Ab', 'Eb', 'Ab'],
    'Abaug' : [None, 'E', 'C', 'G#', None, 'G#'], #[None, 'E', 'C', 'Ab', None, 'Ab'],
    'Abdim' : [None, 'D', 'B', 'F', None, 'G#'], # [None, 'D', 'B', 'F', None, 'Ab']
    'Abmaj7' : [None, 'D#', 'C', 'G', None, 'G#'], #[None, 'Eb', 'C', 'G', None, 'Ab'],
    'Abmin7' : [None, 'D#', 'B', 'F#', None, 'G#'], # [None, 'Eb', 'B', 'Gb', None, 'Ab'],
    'Abdom7' : ['G#', 'D#', 'C', 'F#', 'D#', 'G#'], #['Ab', 'Eb', 'C', 'Gb', 'Eb', 'Ab'],
    'Abmaj9' : ['A#', 'D#', 'C', 'G', None, 'G#'], #['Bb', 'Eb', 'C', 'G', None, 'Ab'],
}